### ISSUE TITLE
Shorthand commands

### ISSUE THREAD

**Issue by paulombcosta** [elm-lang/elm-repl#107]
Would it be interesting shorthand commands like :e to exit the REPL ?. I could submit a PR for it if it's a desirable feature.

**Comment by evancz** [comment]
This proposal is not fleshed out enough to be at the PR phase. I am a fan of using complete names in all circumstances, so the flags to my binaries are even full names. In the case of exit, you can do Ctrl-c twice or Ctrl-d depending on your OS. I think that's a better shortcut.
