### ISSUE TITLE
Man pages

### ISSUE THREAD

**Issue by sassanh** [elm-lang/elm-repl#111]
I don't know if this's right repo for creating this issue, please lead me to right place if I'm wrong.
After installing elm through its installer/homebrew `man elm` doesn't work. What can I do about it? Man pages can be helpful not only for their information, but also for programs like fish shell that build autocompletions based on man pages.

**Comment by jvoigtlaender** [comment]
I think the right repository for this issue would be https://github.com/elm-lang/elm-platform. That's where the Elm installers are made, and certainly creation/install of man pages would have to happen during the install phase of Elm.

**Comment by sassanh** [comment]
@jvoigtlaender thanks, I'll create an issue there. Closed this one.
