### ISSUE TITLE
REPL does not support typing in type annotations

### ISSUE THREAD

**Issue by clozach** [elm-lang/elm-repl#113]
Attempting to use type annotations gives an unhelpful error. E.g.,

``` elm
> fortyTwo : Int
```

…gives…

``` text
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3│   fortyTwo : Int
              ^
I am looking for one of the following things:

    end of input
    whitespace


> names : List String
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3│   names : List String
           ^
I am looking for one of the following things:

    end of input
    whitespace
```

**Suggested solutions**

- *ideal* Build in actual support for this language feature
- *lower effort* Respond to this specific syntax "error" with explicit workaround instructions

**Why it matters**

As I understand it, part of the philosophy behind elm is that community and instruction are nearly as important as the language's features. Simply trying to test out the language syntax in a live context is currently liable to lose potential members of the community, since the current workaround for this issue is to:

1. Turn to Google
2. (Hopefully) discover and read this (closed issue)[https://github.com/elm-lang/elm-repl/issues/75]
3. Completely interrupt the original learning path to learn instead about `elm-make` and/or `elm-reactor`.

The last time I was interrupted like this while trying to learn elm, I ended up having to get back to my day job and didn't come back to exploring elm for months.

**Comment by jvoigtlaender** [comment]
Why open a new issue about this? There's already https://github.com/elm-lang/elm-repl/issues/86. If you have something to add to the discussion, please add it there instead of opening a duplicate.

**Comment by jvoigtlaender** [comment]
Or convince people over there to close their issue, if you think yours makes a better case/argument for the same fact.

**Comment by clozach** [comment]
Ah, you're quite right. I scanned through the open issues (and closed issues) but didn't actually open each one and read it. Being an elm n00b, I didn't make the connection between what I'd seen described as "type annotations" and that issue's title, "Function signature." Thanks!

**Comment by alexdesi** [comment]
After a couple of hours I found out this, I suspect many people that are trying to learn ELM, are using repl to experiment with ELM, and for sure there want to try the annotation, but the message is quite misleading: 

"SYNTAX PROBLEM ...  A single colon is for type annotations. Maybe you want :: instead? Or maybe you
are defining a type annotation, but there is whitespace before it?"

Has this been closed? It seems to me a real issue to work out.

**Comment by jvoigtlaender** [comment]
#86 is open.
