### ISSUE TITLE
Type of record element is written as `number'` instead of `number`

### ISSUE THREAD

**Issue by rudolfb** [elm-lang/elm-repl#116]
If a record has two elements, both of type number, the type displayed for the second number element is `number'` instead of `number`. Note the `'` after the type string `number` in the second type element.

```
> point = { x = 3, y = 4 }
{ x = 3, y = 4 } : { x : number, y : number' }
```

Here a more complex example testing a few permutations. Only in the case where more than one element is a number does this seem to happen.

```
rb@u:~/github/agent_online/web/elm$ elm-repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> point = { x = 1, y = 2 }
{ x = 1, y = 2 } : { x : number, y : number' }
> point = { x = 1, y = 2, a = 3, b = 4 }
{ x = 1, y = 2, a = 3, b = 4 }
    : { a : number, b : number', x : number'', y : number''' }
> point = { x = 1, y = 2, a = 3, b = 4, i = 5, j = 6 }
{ x = 1, y = 2, a = 3, b = 4, i = 5, j = 6 }
    : { a : number
      , b : number'
      , i : number''
      , j : number'''
      , x : number''''
      , y : number'''''
      }
> test = { x = "a", y = 2, a = 3, b = 4, i = 5, j = 6 }
{ x = "a", y = 2, a = 3, b = 4, i = 5, j = 6 }
    : { a : number
      , b : number'
      , i : number''
      , j : number'''
      , x : String
      , y : number''''
      }
> test = { x = "a", y = 2, a = 3, b = 4 }
{ x = "a", y = 2, a = 3, b = 4 }
    : { a : number, b : number', x : String, y : number'' }
> test = { x = "a", y = 2, a = "b", b = 4 }
{ x = "a", y = 2, a = "b", b = 4 }
    : { a : String, b : number, x : String, y : number' }
```

It seems as if this then propogates the error the more elements of type number are added to the record.

**Comment by jvoigtlaender** [comment]
This is not an error at all. It's how types in Elm work. The type of `{x = 3, y = 4}` *is* `{x : number, y : number'}`, which is a generalization of the four possible types `{x : Int, y : Int}`, `{x : Int, y : Float}`, `{x : Float, y : Int}`, `{x : Float, y : Float}`. The fact that the two concrete types of `x` and `y` could be different (`Int` vs. `Float`) is why there needs to be a distinction made between `number` and `number'`.

**Comment by rudolfb** [comment]
@jvoigtlaender Thanks for the explantion. It has taken a while, but I think I understand now. It does look strange tough :-)
