### ISSUE TITLE
Hardware fault on Fedora 22

### ISSUE THREAD

**Issue by soycamo** [elm-lang/elm-repl#120]
When running the REPL, I have some strange behavior. If I type something in, it takes a while to actually do anything. Then if I Ctrl+C, I get an error from Elm.

Here's the terminal output:
```
11:42 me@compy ~ $ elm repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 1 + 2

3 : number
> 
> 
> 
11:45 me@compy ~ $ elm repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 
elm-repl: <stdin>: hGetChar: hardware fault (Input/output error)
```
I am running Fedora 22 with Linux kernel 4.2.8-200.fc22.x86_64. I installed via npm v2.11.3 (nodejs v0.12.7). I installed it with `npm install -g elm`. I had problems installing it because npm doesn't install to the default path for sudo, but I managed to get it to work.

**Comment by evancz** [comment]
Do you feel that #121 is the same thing? If so, I can change the title and body to say that this shows up on Fedora as well.

**Comment by soycamo** [comment]
I think it might be a combination of #121 and something else. I'll open a new bug report if I see something else weird.
