### ISSUE TITLE
Repl broken after entering `True && False`

### ISSUE THREAD

**Issue by LucianU** [elm-lang/elm-repl#123]
I entered `True && False` in the repl, and that broke it. Every time I try to start the repl, I get the error below.

```
> True && False
elm-repl: repl-temp-000.elm: openFile: does not exist (No such file or directory)
lucian@192-168-0-100:~/dev/elm$  elm-repl
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:316:31)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/local/lib/node_modules/elm/binwrappers/elm-repl:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
Repl version: 0.17.1
OS: OS X 10.9.5

**Comment by evancz** [comment]
It seems like this is not specific to the expression you entered. Is it *only* that expression? Or can you do this with other expressions?

**Comment by LucianU** [comment]
I entered other expression prior to that, but that was the last. Unfortunately, I can't give more detail, because now I can't reproduce the issue. Another detail which I didn't mention in my first post is that none of the `elm` commands worked after this error.

**Comment by evancz** [comment]
So everything works now?

**Comment by LucianU** [comment]
Yes, now I can use any of the `elm` commands.

**Comment by evancz** [comment]
Okay. I don't know how we can reproduce this based on the information we have. So I am going to close and hope that someone reports the issue again with additional information. Sorry for the trouble, and I'm glad it ended up working!

**Comment by LucianU** [comment]
Thank you for creating Elm! I love working with it!
