### ISSUE TITLE
Importing long list causes "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/elm-repl#146]
I got this error trying to run tests, as they rely on the repl it seems. Anyway I tracked it down to the import of a file that contains only a 640 item list (of countries and states). I reduced the list to 290 and it worked, but I don't know what is the actual cutoff point.

This has made me think I should move this into asynchronously downloaded json, but the bug still stands I think.

**Comment by rtfeldman** [comment]
> I got this error trying to run tests, as they rely on the repl it seems

`elm-test` doesn't use `elm-repl` at all, so I suspect it's more likely to be https://github.com/elm-lang/elm-compiler/issues/1521
