### ISSUE TITLE
Breaks on any usage of `Element`

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-repl#15]
If you import this from elm-repl,
```haskell
module Test where

foo = asText 3
```
it barfs with: 
`TypeError: Object #<Object> has no method 'createElement'`
This is because the above javascript will trigger a call to `document.createElement`. Some solutions:

1. Have the Elm repo make 2 runtimes: elm-web-runtime.js and elm-bare-runtime.js or elm-node-runtime.js where the latter has web stuff removed/node stuff added.
2. Put `document = document || { createElement: function(args, ...) {} ... }` with a dummy function for everything used in elm-runtime.js. This is fairly brittle without tests because it means we'll need to add a new dummy function for every usage of document.
3. The even hackier version of 2 is to concatenate the line of js mentioned in 2 right onto the front of what's fed into node here: https://github.com/evancz/elm-repl/blob/master/Evaluator.hs#L71 .

I think 1 is the best long-term solution for this, but 2 and 3 will work as temporary hacks for now. Just let me know what you think and I can code this up really quickly.

**Comment by evancz** [comment]
Is the issue that `import Test` fails? Or that `Test.foo` fails? If it was the former, it is resolved now. If it is the latter, it is still an issue. I can't really tell from the comments here though.

**Comment by evancz** [comment]
This should be resolved with the next release of elm-lang/core

**Comment by jvoigtlaender** [comment]
Is this still a current issue?
