### ISSUE TITLE
REPL freezes up, Ellie freezes up too, both freezing the whole system

### ISSUE THREAD

**Issue by endlessoblivion** [elm-lang/elm-repl#159]
An innocent and incorrect line like:
```elm
List.foldl (\a b -> b a) () []
```
or:
```elm
List.foldl (\a b -> b a) (,) []
```
freezes REPL up and after a while the whole system freezes too.

The same happens in Ellie, where compilation of these doesn't finish (ever), eventually freezing the browser and system too.

**Comment by zwilias** [comment]
Thanks for the report!

This looks like it's the same issue as in this bug: https://github.com/elm-lang/elm-compiler/issues/1602

Since it's fixed in 0.19, I'll close this for now.
