### ISSUE TITLE
Use Text instead of ByteString.Char8

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-repl#27]
ByteString.Char8 can cause encoding issues: http://stackoverflow.com/questions/8916107/data-text-vs-data-bytestring-char8 . We should switch to using Text in case source files ever include unicode.

**Comment by evancz** [comment]
Is this still relevant? Is it possible to make this issue more specific so we can address it or close it?

**Comment by evancz** [comment]
Closing until we find a specific issue in the REPL.
