### ISSUE TITLE
Parse error on /=

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-repl#28]
````
> 1 /= 2
[1 of 1] Compiling Repl                ( repl-temp-000.elm )
Parse error at (line 3, column 1):
unexpected "d"
expecting whitespace
````

`main = asText <| 1 /= 2` works fine in Elm itself, so at least *that's* not broken. `1 / 2`  and `1 == 2` work find in the repl.

**Comment by wiserfirst** [comment]
I find operator `/=` still doesn't work in Elm REPL 0.4 (Elm Platform 0.15)
```
> 1 /=2

Error in repl-temp-000.elm:

Parse error at (line 3, column 1):
unexpected "d"
expecting a newline or whitespace
```
And `<=` and `>=` don't work either. So maybe this issue should be re-opened.

**Comment by evancz** [comment]
The latest version of the REPL is 0.4.2. This is the output I am seeing with the latest stuff:

```
$ elm-repl
Elm REPL 0.4.2 (Elm Platform 0.15.1)
  See usage examples at <https://github.com/elm-lang/elm-repl>
  Type :help for help, :exit to exit
> 1 /= 2
True : Bool
> 
```

**Comment by wiserfirst** [comment]
That's great! Thanks

**Comment by mgold** [comment]
Confirmed - great to have this resolved.
