### ISSUE TITLE
"ReferenceError: navigator is not defined" in elm-html apps

### ISSUE THREAD

**Issue by clarkware** [elm-lang/elm-repl#48]
It seems that the elm-html library depends on a JavaScript "navigator" object that isn't defined when an elm-html app is run in the context of the REPL:

```
$ elm-repl
Elm REPL 0.4 <https://github.com/elm-lang/elm-repl#elm-repl>
Type :help for help, :exit to exit
> import Todo
> Todo.initialModel
ReferenceError: navigator is not defined
```

**Comment by evancz** [comment]
@maxsnew or @jcollard, can you take a look at this? It comes up specifically when you have virtual-dom as a dependency.

It looks like there's a list of things needed by virtual-dom [listed on this line](https://github.com/evancz/virtual-dom/blob/master/src/Native/VirtualDom.js#L370). I think we can do the same "dummy field" trick as is done [here](https://github.com/elm-lang/elm-repl/blob/master/src/Eval/Code.hs#L105-L106).

Let me know yes or no, so I can post on elm-dev or the mailing list about this one!

**Comment by maxsnew** [comment]
Sorry but no, I pulled in a giant jsdom dependency to `IO` to avoid doing this kind of stuff.

**Comment by jadski** [comment]
@clarkware : did you find a workaround for this?

**Comment by rtfeldman** [comment]
Nice!

**Comment by evancz** [comment]
Okay, new versions of virtual-dom and elm-html are out that avoid this problem! Thanks for the report, and let me know if you have further troubles.

**Comment by clarkware** [comment]
Excellent - thanks!

**Comment by purcell** [comment]
I now see a different variation of this issue:
```
Elm REPL 0.4.2 (Elm Platform 0.15.1)
  See usage examples at <https://github.com/elm-lang/elm-repl>
  Type :help for help, :exit to exit
> :reset
Environment Reset
> import Whatever exposing (..) 
> thingAfter "a" ["a", "b", "c"]
ReferenceError: requestAnimationFrame is not defined
> 
```

with this set of dependencies:

```
    "dependencies": {
      "elm-lang/core": "2.0.0 <= v < 3.0.0",
      "evancz/elm-effects": "1.0.0 <= v < 2.0.0",
      "evancz/elm-html": "4.0.0 <= v < 5.0.0",
      "evancz/elm-http": "2.0.0 <= v < 3.0.0",
      "evancz/start-app": "2.0.0 <= v < 3.0.0"
    },
```

**Comment by rtfeldman** [comment]
I'd suggest adding this snippet to the `elm-repl` runtime, to polyfill `requestAnimationFrame` for Node:

https://gist.github.com/paulirish/1579671

**Comment by evancz** [comment]
@rtfeldman, is there some PR relevant to fixing this? Or was it just an issue?

**Comment by rtfeldman** [comment]
Don't believe there's a PR; was just suggesting a fix. I've never tried building elm-repl, but could take a stab at it at some point.

**Comment by evancz** [comment]
I just recall a message from you about polyfilling for this particular feature. The root issue is that elm-effects just assumes that rAF is available, so it'd be easy to polyfill and there's already a version in core Native.Runtime that is polyfilled.

**Comment by rtfeldman** [comment]
Oh yeah - we're polyfilling it in production because IE9 doesn't have rAF
either.

I think leaving libraries out of the polyfilling business is the correct
default, but come to think of it I could see wanting to use Elm Effects in
a Node environment down the line anyway...so this might actually be a case
where it makes sense for the library to ensure it's runnable outside the
browser.

**Comment by purcell** [comment]
Yeah, in my case I've got an elm-html app which uses Effects, and as an Elm noob it's not obvious to me why I wouldn't be able to load my elm module into the repl and then play with it, so it'd be great if this worked without needing any magic on my side.

**Comment by purcell** [comment]
Want me to file a separate issue for this? Happy to if it would help to keep track of it.

**Comment by evancz** [comment]
Best would be a PR, it should be 4 lines [like this](https://github.com/elm-lang/core/blob/master/src/Native/Runtime.js#L337-L341).

**Comment by purcell** [comment]
> Best would be a PR, it should be 4 lines like this.

Would that be here: https://github.com/elm-lang/elm-repl/blob/master/src/Eval/Code.hs#L103-L119 ?

**Comment by evancz** [comment]
Probably better [here](https://github.com/evancz/elm-effects/blob/master/src/Native/Effects.js#L14).

I don't totally agree with @rtfeldman about "users should write the polyfill" in our case. It makes sense for JS people, but it's much more of a pain in the ass in our case right now. I also like things to "just work" so I don't mind maintaining this code.
