### ISSUE TITLE
have to use --interpreter flag on default Ubuntu

### ISSUE THREAD

**Issue by hoosierEE** [elm-lang/elm-repl#57]
I'd call this an enhancement or feature request, not a bug.  On Ubuntu 14.04 with nodejs v0.10.25, I have to invoke elm-repl like this:

    elm-repl --interpreter=nodejs

It would be nice if elm-repl looks for nodejs by this name (in addition to whatever it's already doing), since it's the default on Ubuntu.  I also tried aliasing nodejs to just node, but I guess either elm-repl doesn't expand aliases or it's looking for node by some other name.

The workaround is to just alias "elm-repl" to the above line, but I think it would be a sensible default for elm-repl to look a little harder for the nodejs interpreter.

**Comment by evancz** [comment]
That seems reasonable to me. Can you look into how to do that and share that in this issue?

**Comment by hoosierEE** [comment]
I made some tweaks to `Main.hs` and `Flags.hs` [here](https://github.com/hoosierEE/elm-repl/commit/431d9d2d489cee1ac393f8c78bce11bef79c715a) and tried to get it to build on my system, but ran into cabal issues.  Let me know if you want a PR, I felt uneasy sending one for un-compiled/untested source code.

**Comment by evancz** [comment]
Thanks, that narrowed it down for me so it was easy to make the fix!

**Comment by hoosierEE** [comment]
Sweet, thanks for the fix!

**Comment by evancz** [comment]
@hoosierEE, are you able to build from source? [This thread](https://groups.google.com/forum/#!topic/elm-discuss/IQ-OUfxg-qI) makes me worry that the fix does not actually fix things. Do you have opinions or intution or evidence on this?

**Comment by hoosierEE** [comment]
Sorry, I haven't had luck building from source.  I tried a while back, ran into cabal issues and gave up.
