### ISSUE TITLE
Why does elm-repl depend on the existence of elm-package.json?

### ISSUE THREAD

**Issue by CMCDragonkai** [elm-lang/elm-repl#58]
I just started elm-repl and it gave me this error:

```
elm-make: elm-package.json: openBinaryFile: does not exist (No such file or directory)
```

I readded the elm-package.json, and it worked.

Also where does elm-repl store its repl errors? Is this location configurable? I would prefer not to have lots of files littering my home directory.

**Comment by evancz** [comment]
elm-repl is backed by elm-make. This means you can build any packages that are out there. You need elm-package.json to specify which packages you are using, which are at least the core libraries. It is a feature of Elm's package manager that there are no global installs at all, so every project is sandboxed.

The temp files sticking around was a regression that I just fixed and will be out in the next release relatively soon.

Knowing this stuff, is it possible to close this issue or refine the question?

**Comment by evancz** [comment]
Actually, I think #54 addresses the root of this in a clearer way, so I'm going to close this one. Please clarify if that issue does not truly capture what you are looking for!

**Comment by CMCDragonkai** [comment]
It was just unexpected that making elm work required the existence of the json file in the current directory. I haven't used any other REPLs with that requirement. Sometimes I'm using non-development non-elm directories. Also the error is kind of cryptic.

**Comment by evancz** [comment]
Makes sense to me, #54 makes a good case for the same thing.

**Comment by JamesMcMahon** [comment]
At the very least guides that introduce the elm REPL, like https://guide.elm-lang.org/types/reading_types.html should have a quick aside that it needs to be run in a elm project directory.
