### ISSUE TITLE
Error creating ADT in repl

### ISSUE THREAD

**Issue by julianjelfs** [elm-lang/elm-repl#62]
I'm trying to follow along with the Seven More Languages in Seven weeks book chapter on Elm. 

When I start the repl and try to create an ADT as in book I get an error. 

`> data Color = Black | White`

Gives me the following:

```
Error in repl-temp-000.elm:

Parse error at (line 2, column 20):
unexpected '|'
expecting whitespace or end of input
```

I had other similar issues defining functions but perhaps it is all related. 

I installed Elm with npm and seems to be using Elm REPL 0.4 and Elm Platform 0.15.

I am using Ubuntu 14.04.

Obviously I'm a complete Elm beginner so apologies in advance if I'm doing something stupid. 

Thanks.

**Comment by evancz** [comment]
Ah, I see the problem!

The 7 langs book was written for 0.13 I think, so there have been a few minor changes in syntax or function names. In this case, the keyword `data` has been replaced by the keyword `type`, so you need to type the following instead:

```elm
type Color = Black | White
```

There's a ton more about this feature [here](http://elm-lang.org/learn/Union-Types.elm).

Does that clarify things?

**Comment by julianjelfs** [comment]
Ah perfect, that makes sense. I'll bear that in mind if I have any more problems. Thanks very much for the help.

**Comment by evancz** [comment]
No problem!
