### ISSUE TITLE
imports broken as soon as bad import tried

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-repl#64]
$ elm-repl
Elm REPL 0.4.1 (Elm Platform 0.15)
  See usage examples at <https://github.com/elm-lang/elm-repl>
  Type :help for help, :exit to exit
> import Arra
Error when searching for modules imported by module 'Repl':
    Could not find module 'Arra'

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

> import Array
Error when searching for modules imported by module 'Repl':
    Could not find module 'Arra'

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

>

**Comment by evancz** [comment]
Is this still a problem on the master branch? I believe a similar issue was closed recently. Can you find that issue?
