### ISSUE TITLE
once repl is broken, it seems broken for ever (until restart)

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-repl#65]
in a similar vein to https://github.com/elm-lang/elm-repl/issues/64

$ elm-repl
Elm REPL 0.4.1 (Elm Platform 0.15)
  See usage examples at <https://github.com/elm-lang/elm-repl>
  Type :help for help, :exit to exit
> import Array
> a = Array.repeat 1 42
Array.fromList [42] : Array.Array number
> A = Array.repeat 1 42

Error in repl-temp-000.elm:

Error in definition A:
Could not find pattern 'A'.

> a = Array.repeat 1 42

Error in repl-temp-000.elm:

Error in definition A:
Could not find pattern 'A'.

**Comment by evancz** [comment]
Is this still a problem on the master branch? I believe a similar issue was closed recently. Can you find that issue?
