### ISSUE TITLE
Core Language - walkthrough errors in repl

### ISSUE THREAD

**Issue by mikekidder** [elm-lang/elm-repl#66]
Attempting to follow along on website:

```
> bill = { name = "Bill", age = 47 }
{ age = 47, name = "Bill" } : { age : number, name : String }
> under70 {age} = age < 70

Error in repl-temp-000.elm:

Parse error at (line 3, column 15):
unexpected "}"
expecting whitespace, a newline, pattern or "="
```

It works fine in the online compiler

**Comment by evancz** [comment]
I think this is fixed in the latest version of the REPL which should be out within the week!

**Comment by evancz** [comment]
Just confirmed that it is fixed in master, so I am going to close this. Thanks for the report!

**Comment by mikekidder** [comment]
Thanks Evan!
