### ISSUE TITLE
Multi line code doesn't work

### ISSUE THREAD

**Issue by nabilallam** [elm-lang/elm-repl#67]
Hi,
I'm a newbie and I tried to understand the syntax of Elm.
#### Env:
Version: Elm REPL 0.4.2 (Elm Platform 0.15.1)
OS: OSX mavericks
zshell
node/0.12.1

In the guide the example 
```
> over9000 powerLevel = \
|   if powerLevel > 9000 then "It's over 9000!!!" else "meh"
<function>
```
this example leads to 

```
## ERRORS in repl-temp-000.elm #################################################

-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3|   over9000 powerLevel =
                         ^
I am looking for one of the following things:

    end of input
    whitespace
```

I have no idea what the reason can be.
Let me know, if I missend any thing that can help you.
thx

**Comment by tomduncalf** [comment]
You need to add whitespace on the following line for this to work, so first type: `over9000 powerLevel = \`, then press enter, then `  if powerLevel > 9000 then...` - note you shouldn't type the `|`

**Comment by nabilallam** [comment]
Thank you..

**Comment by evancz** [comment]
@nabilallam, are things working? If not, what did you type into the REPL exactly?

**Comment by nabilallam** [comment]
Sorry, forgot to close it.

**Comment by ghannam80** [comment]
Guys , you should make a note about this space at the beginning of 2nd line, it is really hard to spot this one , I ran into it today and the message is complaining about the line before stating that "end of input" or "whitespace" is expected

**Comment by illepic** [comment]
Noting here that after the `|` you MUST manually space over four spaces for indentation.

**Comment by sigu** [comment]
@illepic one space after the `|` worked for me , I dont think you need four
