### ISSUE TITLE
Set.empty prints an empty Dict

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-repl#69]
I'm assuming this happens because they're internally equivalent, but this is certainly surprising!

```
> import Set
> Set.empty
Dict.fromList [] : Dict.Dict comparable ()
```

**Comment by jvoigtlaender** [comment]
This won't happen anymore with the `core` version in the `master` branch, because: https://github.com/elm-lang/core/commit/d4bd4003e9c2a16c0728f8bdd5c80db03819bc52

**Comment by jvoigtlaender** [comment]
Instead, something else (but also a bit strange) will happen for the moment, until https://github.com/elm-lang/core/issues/288 is addressed.

**Comment by evancz** [comment]
@jvoigtlaender, is `toString` updated to do the right thing in the new version? I have forgotten. If so, is it cool to close this issue?

**Comment by jvoigtlaender** [comment]
@evancz, see the [mailing list](https://groups.google.com/d/msg/elm-discuss/e1yoX_MLxEo/nGH0ZEOuCQAJ): that issue is still unaddressed, AFAIK.

**Comment by rtfeldman** [comment]
For what it's worth, it's not just in the REPL; I've also seen this in type errors in the compiler - as in, I'll get a type error that says something like it couldn't unify with a `Dict` when it was actually trying to unify with a `Set`. (I don't have a minimal case to repro that though.)

**Comment by jvoigtlaender** [comment]
@rtfeldman, *that* cannot anymore happen with the `master` version of `core`. Because of the commit I linked to above, which is in the `master` branch.

**Comment by rtfeldman** [comment]
:+1: good to know, thanks!

**Comment by evancz** [comment]
Okay, so is there an issue with the latest version of core? If so, what is it? If it is not the issue described by Richard, can we open a new issue describing it clearly?

**Comment by jvoigtlaender** [comment]
Richard described two issues here:
* printing a `Set` shows something strange
* type-checking a `Set` actually type-checks a `Dict`

The second one is already addresses in the latest version of `core`. The first one is not yet, but is the matter of https://github.com/elm-lang/core/issues/288. So I think this issue here can be closed.

**Comment by rtfeldman** [comment]
Makes sense to me!
