### ISSUE TITLE
Ctrl-C should abort the line, not the REPL session

### ISSUE THREAD

**Issue by ayberkt** [elm-lang/elm-repl#71]
Ctrl-C in ```ghci``` aborts the current line and Ctrl-D aborts the entire REPL session, which is the canonical behavior for REPLs. In ```elm-repl``` Ctrl-C aborts the session, which is becoming increasingly annoying as I'm getting more into elm.

Since this functionality is imported from Haskeline, I couldn't find a fix. But I would definitely appreciate one.

**Comment by evancz** [comment]
What platform are you on? On my mac, I experience the former behavior, ctrl-c for abort computation and ctrl-d for abort session.

**Comment by ayberkt** [comment]
@evancz OS X 10.10 with zshell. So I guess Ctrl-C is just causing a crash which seems to be aborting the session.

**Comment by evancz** [comment]
Is it possible that this is a Haskeline bug related to zshell since things seem to work okay with bash? If so, I'm not sure we'll be able to fix this one.

**Comment by maxsnew** [comment]
I'm getting this on Mac with bash. The error is

```
elm-repl: <stdin>: hGetChar: hardware fault (Input/output error)
```

**Comment by ayberkt** [comment]
@maxsnew same case with me. Are you on iTerm?

**Comment by maxsnew** [comment]
No, default Terminal.

**Comment by vrdhn** [comment]
re: the hardware fault error,
  it went away after i compiled a 1 line program, which installed the elm-lang/core library.
Hope that helps

**Comment by foriequal0** [comment]
It's a elm-repl npm wrapper's issue.
I've made an PR https://github.com/kevva/elm-bin/pull/35

**Comment by evancz** [comment]
Ah, awesome @foriequal0!

I'm not sure how responsive they'll be, so let me know how it goes. Eventually we may have to bring the npm stuff into elm-platform instead of having it as a totally separate community project, but hopefully that's not necessary.

**Comment by foriequal0** [comment]
It's been merged!
https://github.com/kevva/elm-bin/pull/35#event-427189815

**Comment by evancz** [comment]
Whoo, thank you for figuring this out and making the PR!
