### ISSUE TITLE
Can't import anything; "Found multiple modules named 'Basics'

### ISSUE THREAD

**Issue by xhevahir** [elm-lang/elm-repl#73]
I seem unable to import anything into a REPL session. Every time I get this message: "Found multiple modules named 'Basics' Modules with that name were found in the following locations: 
directory ./.Basics.elm
package elm-lang/core.

I'm using elm-repl v0.4, and Elm Platform 0.15 on x64 Linux, installed with the BuildFromSource.hs script.

**Comment by evancz** [comment]
Where are you running the repl?

If you are running it in a clone of elm-lang/core then you probably have the version of Basics from the package catalog *and* the local one.

If you are running it from a clone of `core`, what happens when you do things in some other directory?

**Comment by xhevahir** [comment]
I take it I shouldn't have added elm-repl, elm-make, and so on to my PATH? I'm trying to figure out how to remove them in fish shell now.

**Comment by evancz** [comment]
It should be fine to have them on your PATH.

If you run `pwd` (or whatever the equivalent is in fish) what is that directory? If it is a clone of https://github.com/elm-lang/core/ that explains your issue. If not, we can work from there.

**Comment by xhevahir** [comment]
Ugh, I'm an idiot. Yes, I was running the REPL inside the directory where the standard library was; I had been trying earlier to figure out why I couldn't import files the way I was used to with other languages, and didn't bother leaving it when somebody suggested using modules.

Thank you.

**Comment by evancz** [comment]
No problem, I think you ran into a particularly tricky spot! There are some exceptions made specifically for core, so it's the one time when things are weird :)

In any case, glad we could help get it sorted out! Please don't hesitate to ask if you run into other stuff!
