### ISSUE TITLE
Date.fromString crashes the repl

### ISSUE THREAD

**Issue by agrafix** [elm-lang/elm-repl#74]
```
> import Date as D
> D.fromString "test"
TypeError: undefined is not a function
```

Maybe linked to https://github.com/elm-lang/elm-compiler/issues/1010 ?

**Comment by maxsnew** [comment]
This is fixed on master. You can install it easily using this if you don't want to wait for the next release: https://github.com/elm-lang/elm-platform .

Let me know if that doesn't fix it for you.
