### ISSUE TITLE
Error declaring type - whitespace / end of input

### ISSUE THREAD

**Issue by fineline** [elm-lang/elm-repl#75]
Trying to follow tutorial "Model The Problem", get an error on the line

fortyTwo : Int

as follows

Elm REPL 0.4.2 (Elm Platform 0.15.1)
  See usage examples at <https://github.com/elm-lang/elm-repl>
  Type :help for help, :exit to exit
> fortyTwo : Int
## ERRORS in repl-temp-000.elm #################################################

-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

3|   fortyTwo : Int
              ^
I am looking for one of the following things:

    end of input
    whitespace

**Comment by jonsharratt** [comment]
Just experienced the same issue `Elm REPL 0.4.2 (Elm Platform 0.15.1)`

**Comment by evancz** [comment]
I'd switch over to using elm-make or elm-reactor to follow along that part of the tutorial. Right now the REPL does not support typing in type annotations like that.

Is that enough info to unblock? Please let me know if I can be more helpful!

**Comment by jonsharratt** [comment]
Yer probably would be useful just to tweak the documentation to say so.  If you are following it through step by step as it seems we both were, just throws a spanner in the works.

Thanks for the prompt reply. :+1:

**Comment by fineline** [comment]
Agreed, I'm fine now - have made much more progress moving from REPL to reactor. Probably more of a documentation issue for now. Is the doc open source?
