### ISSUE TITLE
Elm REPL requires non-default packages to do 1+1 ?

### ISSUE THREAD

**Issue by chbrown** [elm-lang/elm-repl#90]
I installed Elm a while ago, and was finally getting back to kicking the tires, so I ran the Mac uninstall script from http://elm-lang.org/install, installed the latest version (0.15.1) via the Mac installer on the same page, and called `elm-repl` at the command line.

> Elm REPL 0.4.2 (Elm Platform 0.15.1)
>  See usage examples at <https://github.com/elm-lang/elm-repl>
>  Type :help for help, :exit to exit

Yay! But then I try to evaluate `1 + 1`, and it says "Unable to find a set of packages that will work with your constraints." Screenshot: http://imgur.com/PoWBXwS

I don't recall it failing so quickly with the previous version I had tried out (0.14.0?), and I've since then installed some portion of cabal and stack — might there be some conflict there?

Or is there a way to get to get Elm to tell me little bit more about the set of packages that _will_ work with the constraints of basic arithmetic?

**Comment by chbrown** [comment]
P.S.: Since my last foray into Elm-land, I've also upgraded Node.js:
> [chbrown@air ~]$ node -v
> v5.0.0

**Comment by chbrown** [comment]
Just retried with Elm `0.16`, similarly installed via the Mac `pkg` installer, and it works! Yay!

**Comment by jvoigtlaender** [comment]
@chbrown, please close this issue.
