### ISSUE TITLE
Colors in error messages

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-repl#93]
`elm make` has lovely colors for error messages, but `elm repl` is monochrome. Would be great if it had colorized ouput too, even if only for error messages!

**Comment by Marqin** [comment]
:+1:

**Comment by maport** [comment]
Is 0.17 supposed to have a coloured `elm repl`?

With my [docker build](https://hub.docker.com/r/codesimple/elm/) of the elm tools I do get colours in `elm make` but not in `elm repl`. I did used to get colours in `elm repl` in 0.16, so I'm not sure if this is a known issue or just something wrong with my build.

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-make/issues/123
