### ISSUE TITLE
1 + 1 fails

### ISSUE THREAD

**Issue by porglezomp** [elm-lang/elm-repl#98]
My freshly installed (with rpm) elm fails like this:
```
> 1 + 1
elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```
My node version is 5.3.0, my elm-repl is 0.16.0.

**Comment by igrep** [comment]
Looks very similar to https://github.com/elm-lang/elm-make/issues/33https://github.com/elm-lang/elm-make/issues/33 .
What's your OS and `LANG`?

**Comment by igrep** [comment]
Oh, and try deleting elm-stuff and reinstall core with `elm package install`.

**Comment by porglezomp** [comment]
I'm on ubuntu 12.04.5 LTS.
Clearing the packages doesn't help any, but I realized that I was setting my `LANG` the wrong way.
```
$ LANG=en_US.UTF-8
$ elm repl
```
doesn't work, but
```
$ LANG=en_US.UTF-8 elm repl
```
works perfectly fine.

For other people who run into this, don't just set the variable, do
```
$ export LANG=en_US.UTF-8
```

**Comment by teaspoon** [comment]
I'm on Ubuntu 14.04. Fresh install.

~$ LANG=en_US.UTF-8 elm-make app/assets/elm/Accounting.elm --output test.js
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
    evancz/elm-html 4.0.2
    evancz/elm-http 3.0.0
    evancz/virtual-dom 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/elm-http
Downloading evancz/virtual-dom
Packages configured successfully!
[=====================                             ] - 16 / 38elm-make: elm-stuff/packages/elm-lang/core/3.0.0/src/Graphics/Element.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation

Super frustrating.

**Comment by jvoigtlaender** [comment]
You do not seem to have tried one of the two ways that the previous poster reported as working:
```bash
$ LANG=en_US.UTF-8 elm repl
```
or
```bash
$ export LANG=en_US.UTF-8
```

**Comment by teaspoon** [comment]
Sorry, only notriced now that this is for elm-repl. I am running elm-make, but neither 
LANG=en_US.UTF-8 elm-make ...
or
export LANG=en_US.UTF-8
works.

**Comment by jvoigtlaender** [comment]
Does `elm-repl` work? If your problem is specific to `elm-make`, it's probably better to bring it up in https://github.com/elm-lang/elm-make/issues/33. There are several people in the discussion there who have experienced similar problems and found varying solutions. Maybe one of them will have advice that applies to your case.

**Comment by jvoigtlaender** [comment]
@porglezomp, it seems this can be closed.

**Comment by porglezomp** [comment]
Sure, :+1:
