### ISSUE TITLE
Elm-repl doesn't gracefully handle ^C

### ISSUE THREAD

**Issue by porglezomp** [elm-lang/elm-repl#99]
To reproduce:
```
$ elm-repl
---- elm repl 0.16.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> ^C
> elmtodo $ 
elm-repl: <stdin>: hGetChar: hardware fault (Input/output error)
```

This should probably be explicitly handled.

**Comment by yurrriq** [comment]
I'm still seeing this in 0.17.0.

**Comment by evancz** [comment]
To make any progress, we need to know which platform this is happening on. Linux? Which distribution?

**Comment by yurrriq** [comment]
@evancz, I've updated my comment with the versions of (seemingly) pertinent software on my system.

**Comment by yurrriq** [comment]
Related: #71, kevva/elm-bin#35, elm-lang/elm-platform#150

**Comment by evancz** [comment]
@yurrriq, did you compile from source? Why mention the GHC version?

If you installed via `npm` it looks like https://github.com/elm-lang/elm-platform/issues/150 would resolve this and we should close this. If not, we should still close this and open a new issue that clearly explains the OS and install route and why https://github.com/elm-lang/elm-platform/issues/150 is not the answer.

**Comment by yurrriq** [comment]
@evancz, I installed Elm via `brew install elm`, using [this formula](https://github.com/Homebrew/homebrew-core/blob/c83fb2f0158a2a848067c51dfaa9b37b80261898/Formula/elm.rb), which, at a glance, appears to build the Elm compiler, if nothing else, from source.

Should I have installed via `npm` instead? This is my first foray into the front end in quite a while..

**Comment by evancz** [comment]
I'm not sure that'll fix it, but only the stuff at http://elm-lang.org/install are actually made by me or people I work with. The `brew` version is done by someone in the world who I do not know or coordinate with. So next steps should be:

  1. Try the `.pkg` or `npm` installer. See if there is still a problem.
  2. If yes, open a new issue (following [the checklist](https://github.com/process-bot/contribution-checklist/blob/master/issues.md)) that describes the results given each install path.
  3. If no, probably open an issue with the `brew` people who made this thing?

P.S. I am on the exact same version of OS X and things are working fine for me.

**Comment by evancz** [comment]
Also, welcome back! Thanks for working through this issue with me. I know you don't have to do this kind of thing, and I hope you enjoy the parts of Elm that are actually on the front-end ;)

**Comment by yurrriq** [comment]
I'm getting the same experience irrespective of installion method. 😿

| Installation Method | Result | Extra Info |
| --- | --- | --- |
| [`brew install elm`](https://github.com/Homebrew/homebrew-core/blob/c83fb2f0158a2a848067c51dfaa9b37b80261898/Formula/elm.rb) | 👎 | `sh` [uninstall.sh](https://github.com/elm-lang/elm-platform/blob/master/installers/mac/helper-scripts/uninstall.sh) first |
| [`Elm-Platform-0.17.1.pkg`](http://install.elm-lang.org/Elm-Platform-0.17.1.pkg) | 👎 | `brew unlink elm` first |
| `npm install -g elm` | 👎 | `sh` [uninstall.sh](https://github.com/elm-lang/elm-platform/blob/master/installers/mac/helper-scripts/uninstall.sh) first; `node v6.2.2`, `npm 3.10.3` |
| [Build from source](https://github.com/elm-lang/elm-platform) | ❓ | Don't have time right now |

**Comment by evancz** [comment]
Started an issue putting all the info in one place. Maybe we'll get info from others.

**Comment by nickdima** [comment]
Installed elm on Mac OS by downloading the setup from the site. ctrl + c doesn't seem to do anything in zsh. I'm using iTerm.
